# Setup
title: Future Gadget Lab
description: El Psy Congroo
url: https://jovinus.github.io
avatar: /lab_logo.png
paginate: 5
permalink: pretty
cover_image: /blog_bg.png

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: KyungHyunL
  card: summary
logo: logo.png
social:
  name: KyungHyun Jovinus Lee
  links:
    - https://twitter.com/KyunghyunL
    - https://github.com/Jovinus
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: KyungHyun Jovinus Lee
  url: https://github.com/Jovinus/
  email: lkh256@gmail.com
